BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBB XXXXX BBBBBBBB BBBBB

BBBBB BBBBBBBBBBB
  
  XXXX XXXXXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBB

BBBBB BBBBBBBBBBXXXXXBBBBBBBB BBBBBBBBBB

BBBBB BBBB
  XXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXXXXX XXXXXXXXX
            XXXXX
               
            XXXXXX
            XXXXX
               
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXX XX
                XXXXXX
            XXXXXX
            BB BBBBBBBBBBB
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXXXXX XXXX XXXX XXX XXXXXXXXXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXX
              XXXX

              XXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XX

              XXXXX
                XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXXX XXXX XXXXX XXXXXX X XXXXXX XXXXXX XXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXXX
        XXXXXXXXXX
      XXXXXX
      
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
            XXXXXXXXXX XXXXXXXXXXXX
            XXXXX
              XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
            XXXXXX
            XXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
            XXXXXX
            XXXXX
              XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
            XXXXXX
            XXXXX
              XX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XX XXXX
              XXXX

              XXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXX XX

              XXXXX
                XXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                XXXXXXXX XXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XX X XXXXXXXXX X XXXXXXXXX XXXXXXX XXX XXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXXX
        XXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB BBBB
