# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-08 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20180117_2121'),
        ('project', '0014_auto_20180118_0929'),
    ]

    operations = [
    ]
