# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-08 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20190108_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='phase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Phase'),
        ),
    ]
