# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-09 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_historicaltask_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True},
        ),
    ]
