# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-09 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20190109_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='phase',
        ),
        migrations.AddField(
            model_name='task',
            name='assignedto',
            field=models.ForeignKey(blank=True, db_column='assignedto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Emp3', to='project.Employee', to_field='empid'),
        ),
        migrations.AddField(
            model_name='task',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Emp4', to='project.Employee', to_field='empid'),
        ),
        migrations.AddField(
            model_name='task',
            name='departement',
            field=models.ForeignKey(blank=True, db_column='departementid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Department', to_field='deptcode'),
        ),
        migrations.AddField(
            model_name='task',
            name='lasteditby',
            field=models.ForeignKey(blank=True, db_column='LastEditBy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Task_Employee_LastEditBy', to='project.Employee', to_field='empid'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, db_column='projectid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
    ]
