# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-09 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20190109_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ProjectStatus'),
        ),
    ]
