# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-14 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_projectphase_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.ProjectPhase'),
        ),
    ]
