# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-14 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20190114_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_phases', to='project.Employee', to_field='empid'),
        ),
    ]
