# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-14 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20190114_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ProjectPhase'),
        ),
    ]
