# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-20 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_media_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='phase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.ProjectPhase'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='projects',
            field=models.ManyToManyField(through='project.ProjectPhase', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase_details', to='project.Phase'),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectPhase'),
        ),
    ]
