# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_auto_20190121_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='dependent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='dependent',
            field=models.BooleanField(default=False),
        ),
    ]
