# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-21 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20190121_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='/documents'),
        ),
    ]
